"""new data

Revision ID: 3ee7c5a1c4bb
Revises: 3e3bbbd75f05
Create Date: 2023-05-24 09:08:03.245234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee7c5a1c4bb'
down_revision = '3e3bbbd75f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantsdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_latin', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('plant_type', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('watering_96h', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('watering_72h', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('light_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_moisture', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('areas', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('plant_needs', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('characteristics', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantsdata', schema=None) as batch_op:
        batch_op.drop_column('characteristics')
        batch_op.drop_column('plant_needs')
        batch_op.drop_column('areas')
        batch_op.drop_column('min_moisture')
        batch_op.drop_column('light_level')
        batch_op.drop_column('quantity')
        batch_op.drop_column('watering_72h')
        batch_op.drop_column('watering_96h')
        batch_op.drop_column('plant_type')
        batch_op.drop_column('name_latin')

    # ### end Alembic commands ###
