"""sensor position test

Revision ID: 3e3bbbd75f05
Revises: 7c8daaaa1ee7
Create Date: 2023-04-24 07:53:16.522333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3bbbd75f05'
down_revision = '7c8daaaa1ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('panel', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('line', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sensorNum', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('sensorNum')
        batch_op.drop_column('line')
        batch_op.drop_column('panel')

    # ### end Alembic commands ###
